# Generated by Django 4.2.7 on 2026-01-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email пользователя')),
                ('room_number', models.CharField(max_length=50, verbose_name='Номер аудитории')),
                ('booking_date', models.DateField(verbose_name='Дата бронирования')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('booking_type', models.CharField(choices=[('lesson', 'Занятие'), ('exam', 'Экзамен'), ('meeting', 'Собрание')], default='lesson', max_length=20, verbose_name='Тип бронирования')),
                ('purpose', models.TextField(blank=True, verbose_name='Цель бронирования')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('availability_check_response', models.JSONField(blank=True, null=True, verbose_name='Ответ от сервиса доступности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
